// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVE4j_sx36bm7YgzbTxThoP-2cP8AqgJY',
    appId: '1:1093257041401:android:d876fe19413f87474a9928',
    messagingSenderId: '1093257041401',
    projectId: 'fyp-anemometer',
    databaseURL: 'https://fyp-anemometer-default-rtdb.firebaseio.com',
    storageBucket: 'fyp-anemometer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlxnZeZmDxU2ekkwFBxFE7LwBYyo-9DEc',
    appId: '1:1093257041401:ios:4d4b91e955c10d074a9928',
    messagingSenderId: '1093257041401',
    projectId: 'fyp-anemometer',
    databaseURL: 'https://fyp-anemometer-default-rtdb.firebaseio.com',
    storageBucket: 'fyp-anemometer.appspot.com',
    iosClientId: '1093257041401-s0ve2m3amet4uaej1riigeb28pmecapa.apps.googleusercontent.com',
    iosBundleId: 'com.bkc17.fyp1',
  );
}
